Router
mishanya1111/ReactMG pull request #10
Opened 2024-10-28 15:52 UTC by mishanya1111

2024-11-04 10:14 UTC, msilina-ibagroup-eu commented
насколько я понимаю, эта папка содержит pages
![image](https://github.com/user-attachments/assets/17bf120b-f27b-479f-8972-a51065106f15)

2024-11-04 10:14 UTC, msilina-ibagroup-eu reviewed
повторное ревью

2024-11-04 10:14 UTC, msilina-ibagroup-eu commented on src/Router/NotFoundPage.js
> +    const error = useRouteError();
у тебя есть error, которая содержит status и statusText, но ты, почему-то, эти значения не используешь

2024-11-04 10:14 UTC, msilina-ibagroup-eu commented on src/Router/Root.js
> +            <div className="navbar">
вынеси навиацию в отдельный компонент

2024-11-04 10:14 UTC, msilina-ibagroup-eu commented on src/index.js
> +import { createBrowserRouter, RouterProvider } from 'react-router-dom';
все это должно быть в  App компоненте

вынеси header из App в отдельный компонент и создай отдельную страницу, которая будет рендерить header и cards

2024-11-04 10:18 UTC, msilina-ibagroup-eu commented
сделай отступы одинаковыми и выровняй кнопку
![image](https://github.com/user-attachments/assets/697755d1-6da5-49ab-9fa7-8aca6e1e1fef)

2024-11-12 09:50 UTC, msilina-ibagroup-eu requested changes

2024-11-12 09:50 UTC, msilina-ibagroup-eu commented on src/App.js
> +        path: '/',
`Add links to the "Home" (the page where the cards are displayed) and "Login" pages on the application header.`
Login page должна быть доступна по пути '/login' - login не должен быть 'Home' страницей

2024-11-12 10:43 UTC, mishanya1111 commented on src/App.js
> +        path: '/',
> `Add links to the "Home" (the page where the cards are displayed) and "Login" pages on the application header.`
> Login page должна быть доступна по пути '/login' - login не должен быть 'Home' страницей 

Что у меня должно отображаться на вкладке home? Только навигация?

2024-11-12 13:36 UTC, msilina-ibagroup-eu commented on src/App.js
> +        path: '/',
`"Home" (the page where the cards are displayed)` - должны отображаться карточки

2024-11-15 12:45 UTC, msilina-ibagroup-eu commented on src/App.js
> +        path: '/',
тебе не нужен буквально `/home` путь. `/home` обычно эквивалентен `/`. Home - это стартовая страница. Для твоего приложения стартовая страница - это страница, на которой отображаются карточки.
т.е. карточки должны быть доступны по пути `/`, а логин - по пути `/login`

2024-11-18 10:46 UTC, msilina-ibagroup-eu approved these changes
у тебя логин редиректит по пути, которого не существует
поправь и мерж

2024-11-19 10:12 UTC, merged