EditButton
mishanya1111/ReactMG pull request #2
Opened 2024-08-08 13:32 UTC by mishanya1111

2024-08-12 08:14 UTC, msilina-ibagroup-eu commented
Сделай так, чтобы кнопки Save и Cancel отображались одновременно. Я не могу отменить свои изменения и вернуть все, как было
![image](https://github.com/user-attachments/assets/a585a081-8e8d-4280-990e-d15282fd0618)

Не лучшая идея сохранять jsx в стейте (`setButton(<>Save<FaSave/></>)`). У тебя уже есть `editing`, который можно использовать для отображения нужных кнопок.

Вынеси стили в css файл

Насчет checkbox: будет лучше использовать useState не для стилей, а для состояния checkbox (checked), и, в зависимости от него, применять стили. Пригодится в следующих тасках.

https://github.com/airbnb/javascript/tree/master/react - ознакомься, если еще не ознакомился, и поправь форматирование

2024-08-14 09:17 UTC, msilina-ibagroup-eu requested changes

2024-08-14 09:17 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    const [checkState_, setCheckState] = new useState(false);
откуда взялось `new`? зачем нижнее подчеркивание в конце? зачем в названии state?
`const [checked, setChecked] = useState(false);`

2024-08-14 09:17 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    const [saveInf, editSaveInf] = useState({
создай 2 отдельных состояния для сохраненных значений title и text

2024-08-14 09:17 UTC, msilina-ibagroup-eu commented on src/Card.js
> +        setCheckState((check) => !check);
setCheckState(!checkState_);

2024-08-14 09:17 UTC, msilina-ibagroup-eu commented on src/Card.js
> +        setEditing((edit) => !edit);
setEditing(!editing);

2024-08-14 09:17 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    function setSaveInf() {
у тебя должны быть:
- submitHandler - устанавливает editing = false и новые значения title и text
- editHandler - устанавливает editing = true и checked = false
- cancelHandler - устанавливает editing = false и "возвращает" значения title и text

2024-08-14 09:17 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    return (
для удобства можешь вынести в отдельные функции (RenderEditContent, RenderDefaulContent), можешь все сразу в return писать
```
{ editing ? (
    // отображаешь input для title
    // кнопки Save и Cancel
    // textarea для text
) : (
    // checkbox
    // Edit button
    //<h2>{title}</h2>
    // <p>{text}</p>
) }
```

2024-08-14 21:13 UTC, mishanya1111 commented on src/Card.js
> +    const [checkState_, setCheckState] = new useState(false);
checkState это зарезервированное слово, поэтому и не мог его использовать, и у меня снова не пришло  уведомления на почту(

2024-08-14 21:22 UTC, mishanya1111 commented on src/Card.js
> +    const [saveInf, editSaveInf] = useState({
не до конца понял задумку. интересно почему так

2024-08-14 21:25 UTC, mishanya1111 commented on src/Card.js
> +        setCheckState((check) => !check);
(если не против ,я оставлю. Если против заранее извиняюсь)
сделаю пометку что это придумал не я)
там в курсах показывали что если 2 раза подряд такой код запустить то он только 1 раз сработает, а может быть я что-то путаю

2024-08-14 21:47 UTC, mishanya1111 commented on src/Card.js
> +    const [checkState_, setCheckState] = new useState(false);
установил приложения гита на телефон, вроде должно теперь напрямую приходить

2024-08-15 07:52 UTC, msilina-ibagroup-eu commented on src/Card.js
> +        setCheckState((check) => !check);
не против, оставляй
просто в данной ситуации стейт будет актуальным в момент обновления (он не обновляется асинхронно и т.д.), т.е. ты можешь быть уверен, что он не обновится несколько раз и ты получишь актуальное значение.

2024-08-15 08:49 UTC, msilina-ibagroup-eu commented
Фокус теряется из-за того, что RenderDefaulContent и RenderEditContent создаются заново при каждом рендере. Если писать прямо в return, React сохраняет ссылки на элементы DOM. Просто напиши все в return
```
{ editing ? (
    ...
) : (
    ...
) }
```
Иначе придется использовать refs для input и textarea, для данного таска это избыточно. Потом все равно менять придется

2024-08-15 08:50 UTC, msilina-ibagroup-eu approved these changes
поправт замечания и мерж

2024-08-15 08:50 UTC, msilina-ibagroup-eu commented on src/Card.js
> +        changeEditing();
editing всегда false
 `setEditing(false);`

2024-08-15 08:50 UTC, msilina-ibagroup-eu commented on src/Card.js
> +        changeEditing();
editing всегда false
`setEditing(false);`

2024-08-15 08:50 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    function editingHandler() {
checked всегда false
editing всегда true

2024-08-15 08:50 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    const [saveTitle, setSaveTitle] = useState(firstText);
`const [saveTitle, setSaveTitle] = useState(firstTitle);`

2024-08-15 16:09 UTC, merged