View only
mishanya1111/ReactMG pull request #3
Opened 2024-08-19 10:39 UTC by mishanya1111

2024-08-20 09:44 UTC, msilina-ibagroup-eu commented
сделай так, чтобы чекбокс не скакал туда-сюда, когда ты кликаешь на view only
![image](https://github.com/user-attachments/assets/8029c61b-4ea5-41b9-a528-4b60bdfdd62d)
![image](https://github.com/user-attachments/assets/35076382-71ab-453b-a3bb-5ad4220cc118)

например, размести его с правого краю

2024-08-20 09:46 UTC, msilina-ibagroup-eu commented
![image](https://github.com/user-attachments/assets/821d6027-c40f-448d-bb7c-016cf255a4cf)

2024-08-20 09:46 UTC, msilina-ibagroup-eu requested changes
повторное ревью

2024-08-20 09:46 UTC, msilina-ibagroup-eu commented on src/App.js
> +                <Card baseStyle="borderBox" alternativeStyle="yellowBox"
стили borderBox и yellowBox относятся только к Card. Нет смысла передавать их из App.
создай файл Card.css и используй его в Card.js

Cards должны рендериться динамически, чтобы не нужно было каждый раз руками что-то дописывать. Ну и их может быть гораздо больше.
создай отдельный файл с данными:
```
const cardsData = [
    {
        id: ...,
        title: ....,
        text: ...,
    },
    ...
];
```
и используй эти данные для рендеринга карточек

2024-08-20 09:46 UTC, msilina-ibagroup-eu commented on src/Card.js
> +function Card({baseStyle, alternativeStyle, firstTitle, firstText, checkViewOnly}) {
по сути, когда checkViewOnly (лучше переименуй в что-то вроде viewOnlyChecked) равен true, тебе нужно выйти из режима редактирования, не сохраняя изменения, которые могли вноситься в карточки.
используй для этого useEffect

2024-09-09 11:16 UTC, msilina-ibagroup-eu requested changes
повторное ревью

2024-09-09 11:16 UTC, msilina-ibagroup-eu commented on src/App.js
> +    const cardsData = [
это не отдельный файл

2024-09-09 11:16 UTC, msilina-ibagroup-eu commented on src/App.js
> +    const arrayCards = cardsData.map((card) => <Card viewOnlyChecked={checked} firstTitle={card.title} firstText={card.text} /> )
у каждой карточки должен быть уникальный ключ
![image](https://github.com/user-attachments/assets/ad4aa3d0-dac2-4a34-82a7-6f2f12315f15)

2024-09-09 11:16 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    useEffect(() => {
```
useEffect(() => {
   someFunction();
}, [someValue1, someValue2, ...]);
```
useEffect сработает при изменении значений переменных, которые передаются в массиве. Т.е. someFunction будет вызвана каждый раз, когда изменится одно из значений массива.
в твоем случае нужно проверить значение viewOnlyChecked. И, если ее значение меняется (пользователь кликает чекбокс), необходимо выполнять соответствующее действие.

2024-09-09 11:16 UTC, msilina-ibagroup-eu commented on src/Card.js
> +                {viewOnlyChecked && cancelButton()}
viewOnlyChecked флаг нужен для того, чтобы отображать/скрывать кнопки

2024-09-09 11:16 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    const baseStyle="borderBox";
нет никакой нужды создавать эти переменные

2024-09-10 19:56 UTC, mishanya1111 commented on src/Card.js
> +    const baseStyle="borderBox";
Оно используется в 4 местах. Я могу убрать если надо.

2024-09-11 08:49 UTC, msilina-ibagroup-eu commented on src/Card.js
> +    const baseStyle="borderBox";
какая разница, в скольких местах они используются, если все, что они делают - это хранят стиль из css файла, ничего с ним не далая?
```<div className={checked ? alternativeStyle + ' textDiv' : baseStyle + ' textDiv'}>```
textDiv можно (и нужно) писать напрямую, а borderBox нет?

2024-09-11 09:02 UTC, msilina-ibagroup-eu commented
ради всего святого - почитай уже док https://github.com/airbnb/javascript/tree/master/react
пример:
```
const arrayCards = cardsData.map((card) =>
    <Card
        viewOnlyChecked={checked}
        firstTitle={card.title}
        firstText={card.text}
        key={card.id}
    />
);
```

```
<div style={{width:80}}>
    {viewOnlyChecked &&
        <button
            onClick={editingHandler}
            className="editButton">
            Edit<AiOutlineEdit />
        </button>
    }
</div>
```

2024-09-11 09:02 UTC, msilina-ibagroup-eu approved these changes
поправить и мерж

2024-09-13 09:48 UTC, merged