Split
mishanya1111/ReactMG pull request #4
Opened 2024-09-13 16:37 UTC by mishanya1111

Разделение на CardHeader и CardBody

2024-09-13 16:40 UTC, mishanya1111 commented
как лучше располагать входные данные?
`function CardHeader({
                        editing,
                        checked,
                        viewOnlyChecked,
                        alternativeStyle,
                        baseStyle,
                        firstTitle,
                        setCanselTemp,
                        setEditing,
                        setChecked
                    }) {
                    ...
                    }` 
                    или так 
                    
`function CardHeader({editing, checked, viewOnlyChecked, alternativeStyle, baseStyle, firstTitle, setCanselTemp, setEditing, setChecked}) {
                    ...
                    }`

2024-09-14 07:25 UTC, mishanya1111 commented
Отмена, Я не все сделал (удаление карточек)

2024-09-16 15:27 UTC, msilina-ibagroup-eu commented
```
const CardHeader = ({
    editing,
    checked,
    viewOnlyChecked,
    alternativeStyle,
    baseStyle,
    firstTitle,
    setCanselTemp,
    setEditing,
    setChecked
}) => {
    ...
}
```
или

```
const CardHeader = (props) => {
    ...
}
```

2024-09-16 15:27 UTC, msilina-ibagroup-eu commented
я не вижу CardList

2024-09-16 15:30 UTC, msilina-ibagroup-eu requested changes
доделать таск

2024-09-16 15:33 UTC, mishanya1111 commented
Действительно не сделал. Я не до конца понимаю для чего он нужен. Просто чтобы в нем были все card?

2024-09-17 11:16 UTC, msilina-ibagroup-eu commented
> Действительно не сделал. Я не до конца понимаю для чего он нужен. Просто чтобы в нем были все card?

это best practice
в реакт строят более сложные компоненты, комбинируя простые. Это делает код более модульным и поддердживаемым. С помощью компонентов интерфейс делится на отдельные блоки, кадждый из которых отвечает за свою часть функционала.
если тебе нужно на 10 страницах отображать карточки с различными данными, ты просто можешь переиспользовать CardList компонент с необходимыми данными, вместо того, чтобы копировать и вставлять одинаковый код в разные части приложения => получаешь более организованное и масштабируемое приложение

2024-09-18 08:27 UTC, msilina-ibagroup-eu commented
```Create a "CardList" component that should render "Card" components.```
создать новый компонент, который будет рендерить карточки

если что-то конкретно не понятно - уточни. Я не понимаю, что именно нужно пояснить

2024-09-18 13:28 UTC, msilina-ibagroup-eu commented
CardHeader and CardBody получают нужные пропсы из Card. В том числе все необходимые хендлеры. Например:
```
const CardBody = ({ value, isEditMode, onChange }) =>
    isEditMode ? (
        ...
    ) : (
        ...
    );
};

const CardHeader = ({
    isActive, //  выбрана ли карточка для удаления
    isEditMode, // находится ли карточка в режиме редактирования
    isDisableMode, // доступна ли карточка для редактирования
    value,
    onEdit,
    onChange,
    onCancel,
    onSubmit,
    onChecked
}) => {
    ...
}
```

 onEdit, onChange, onCancel, onSubmit, onChecked - передаются из Card
```
const Card = ({
    id,
    isDisableMode,
    isActive, 
    text, 
    title,
    onChecked
}) => {
    ...
   // for example
   const cancelHandler = () => {
        setTitle(saveTitle);
        setText(saveText);
        setEditing(false);
    }

    return (
        ...
        <CardHeader
            onCancel={cancelHandler}
            ...
        />
        <CardBody
            ...
        />
    )
}
```
CardList получает данные, что позволяет использовать его для рендеринга карточек, содержащих какие угодгно данные
```
const CardList = ({
    items,
    isDisableMode, 
    onChecked
}) => {
    ...
    {items.map(...)}
}
```
для начала, сделай немного проще: добавь к данным карточек флаг isActive
разберешся с этим - можешь использовать другой способ
```
{
    id: 1,
    title: "React",
    text: "Some text",
    isActive: false,
},
```

```
const App = props => {
    ...
    const [data, setData] = useState(cards);
    
    const changeActiveHandler = (id) => {
        // меняет значение isActive для карточки с данным id
    }

    const deleteHandler = () => {
        // удаляет карточки (isActive = true)
    }

    return (
        ...
        <button
            ...
            onClick={deleteHandler}
        >
            Delete cards
        </button>
        ...
        <CardList
            ...
            items={data}
            onChange={changeActiveHandler}
        />
    )
}
```

2024-09-20 09:42 UTC, msilina-ibagroup-eu commented
1. установи prettier
2. создай файл .prettierc
```
{
    "endOfLine": "auto",
    "printWidth": 85,
    "useTabs": false,
    "tabWidth": 4,
    "singleQuote": true,
    "trailingComma": "none",
    "arrowParens": "avoid"
}
```
3. добавь в package.json в scripts команду
```
"format": "prettier --write \"./src/**/*.{js,md,scss}\""
```
4. запусти команду 
```
npm run format
```

2024-09-20 09:54 UTC, msilina-ibagroup-eu reviewed
повторное ревью

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/App.js
> +    const changeActiveHandler = (id) => {
```
const changeActiveHandler = id => {
    setData(cards =>
        cards.map(card => {
            if (card.id === id) {
                const prev = { ...card };
                prev.isActive = !card.isActive;
                return prev;
            }
            return card;
        })
    );
};
```

необходимо создавать копию объекта, чтобы сохранить иммутабельность данных
в React обновления состояния отслеживаются через сравнение предыдущего и текущего состояния. Если менять объект напрямую, React может не заметить изменения (что может привести к непредсказуемым последствиям), поскольку ссылка на объект остаётся прежней. Когда создаётся новая копия объекта, меняется его ссылка => состояние изменилось, и компонент перерисовывается.

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/CardsComponent/Card.js
> +    const baseStyle="borderBox";
убери

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/CardsComponent/Card.js
> +    const alternativeStyle= "yellowBox";
убери

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/CardsComponent/Card.js
> +                alternativeStyle={alternativeStyle}
убери

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/CardsComponent/Card.js
> +                baseStyle={baseStyle}
убери

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/CardsComponent/Card.js
> +                alternativeStyle={alternativeStyle}
убери

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/CardsComponent/Card.js
> +                baseStyle={baseStyle}
убери

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/CardsComponent/CardBody.js
> +                      alternativeStyle,
используй стили напрямую из css файла

2024-09-20 09:54 UTC, msilina-ibagroup-eu commented on src/CardsComponent/CardHeader.js
> +                        alternativeStyle,
используй стили напрямую из css файла

2024-09-20 10:38 UTC, mishanya1111 commented
> 2\. prettierc



> 1. установи prettier
> 2. создай файл .prettierc
> 
> ```
> {
>     "endOfLine": "auto",
>     "printWidth": 85,
>     "useTabs": false,
>     "tabWidth": 4,
>     "singleQuote": true,
>     "trailingComma": "none",
>     "arrowParens": "avoid"
> }
> ```
> 
> 3. добавь в package.json в scripts команду
> 
> ```
> "format": "prettier --write \"./src/**/*.{js,md,scss}\""
> ```
> 
> 4. запусти команду
> 
> ```
> npm run format
> ```

2024-09-20 11:15 UTC, mishanya1111 commented
> 1. установи prettier
> 2. создай файл .prettierc
> ```
> {
>     "endOfLine": "auto",
>     "printWidth": 85,
>     "useTabs": false,
>     "tabWidth": 4,
>     "singleQuote": true,
>     "trailingComma": "none",
>     "arrowParens": "avoid"
> }
> ```
> 3. добавь в package.json в scripts команду
> ```
> "format": "prettier --write \"./src/**/*.{js,md,scss}\""
> ```
> 4. запусти команду 
> ```
> npm run format
> ```


Я не уверен что она запустилась, потому что я работаю в webstorm , и там только можно изменить конфигурацию. Как мне проверить установилось ли?

2024-09-20 11:16 UTC, mishanya1111 commented
Я случайно закрыл пул реквест?

2024-09-20 11:35 UTC, msilina-ibagroup-eu commented
> Я не уверен что она запустилась, потому что я работаю в webstorm , и там только можно изменить конфигурацию. Как мне проверить установилось ли?

если в package.json в dependencies или devDependencies появилась устанавливаемая библиотека, значит она установилась

2024-09-22 10:51 UTC, mishanya1111 commented
С prettier я так и не смог разобраться, потому что в конфигурации так сделать нельяз(npm run format), а в локальной консоли оно не видит команды npm 
![image](https://github.com/user-attachments/assets/b95f6c06-1d5f-4bcb-8e37-c87c627823d0)
Но зато нашёл баг, если ты нажимаешь на checkBox, а потом нажимаешь  на edit (фактически слетает стиль), должно слететь и id для удаление , но оно не уходит, поэтому при нажатии удалить оно удаляет

2024-09-22 11:24 UTC, mishanya1111 commented
Я попытался как плагин установить, но оно вроде всё равно не работает.
![image](https://github.com/user-attachments/assets/95fbcf00-897c-4f96-8776-828e38a3020f)

2024-09-23 09:26 UTC, msilina-ibagroup-eu commented
1. установи Node.js (https://nodejs.org/en/download/prebuilt-installer)
2. для верности перезагрузи компьютер
3. установи prettier (npm i prettier)
4. в package.json должен отобразиться новый пакет и версия
![image](https://github.com/user-attachments/assets/9bbb766a-5491-4a5a-95e8-ea1354e7ad88)

5. создай файл .prettierc
```
{
    "endOfLine": "auto",
    "printWidth": 85,
    "useTabs": false,
    "tabWidth": 4,
    "singleQuote": true,
    "trailingComma": "none",
    "arrowParens": "avoid"
}
```
6. добавь в package.json в scripts команду
```
"format": "prettier --write \"./src/**/*.{js,md,scss}\""
```
7. запусти команду 
```
npm run format
```

2024-09-23 09:29 UTC, msilina-ibagroup-eu requested changes
повторное ревью отформатированного кода

2024-09-24 08:51 UTC, msilina-ibagroup-eu approved these changes
у тебя отступы стали 2 пробела вместо 4. Этого не должно было случиться ("tabWidth": 4)
попробуй проверить настройки IDE

2024-09-25 09:45 UTC, merged