Button Add
mishanya1111/ReactMG pull request #5
Opened 2024-09-25 10:25 UTC by mishanya1111

добавлена функция добавления карточки

2024-09-25 14:17 UTC, msilina-ibagroup-eu requested changes
команда `npm run format` нужна для того, чтобы приводить твой код в нормальный вид
запускай ее после того, как вносишь изменения

используй либо стрелочные функции, либо обычные

2024-09-25 14:17 UTC, msilina-ibagroup-eu commented on src/App.js
> +            id: 9,
зачем нужна uuid, если ты статически задаешь id для каждой создаваемой карточки?
id должен быть уникальным для каждой карточки

![image](https://github.com/user-attachments/assets/c98b541c-fffe-4357-a2f8-01aff1edc5ba)

2024-09-26 10:53 UTC, mishanya1111 commented on src/App.js
> +            id: 9,
Это я тестировал и забыл исправить на uiid😅

2024-09-26 10:55 UTC, mishanya1111 commented
> команда `npm run format` нужна для того, чтобы приводить твой код в нормальный вид
> запускай ее после того, как вносишь изменения
> 
> используй либо стрелочные функции, либо обычные


Если я правильно помню оно само работает, при изменении файла(у меня ctrl + L (форматирование от web storm) не работает нормально). Сегодня это проверю

2024-09-27 06:40 UTC, mishanya1111 commented
> > команда `npm run format` нужна для того, чтобы приводить твой код в нормальный вид
> > запускай ее после того, как вносишь изменения
> > используй либо стрелочные функции, либо обычные
> 
> Если я правильно помню оно само работает, при изменении файла(у меня ctrl + L (форматирование от web storm) не работает нормально). Сегодня это проверю

a нет я не прав, оно само не делает, сейчас попробую погуглить

2024-09-27 10:27 UTC, msilina-ibagroup-eu approved these changes
merge

2024-09-27 10:35 UTC, merged