Http Requests
mishanya1111/ReactMG pull request #9
Opened 2024-10-11 15:14 UTC by mishanya1111

2024-10-14 09:49 UTC, msilina-ibagroup-eu reviewed
добавить обработку ошибок (отображать сообшение об ошибке)

2024-10-14 09:49 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +                .filter(el => el.Number < 16)
в данном случае лучше использовать slice. Если Number изменится, ты не получишь 15 элементов, поэтому лучше не учитывать значение Number
к тому же тебе, по сути, не нужно проверять каждый элемент, но приходится лишний раз проходить через все элементы

2024-10-16 09:00 UTC, msilina-ibagroup-eu reviewed
откати изменения в withLoadingDelay и не используй его в CardList
используй флаг fetching для отображенияч спинера

2024-10-16 09:00 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +    const [fetching, setFetching] = useState(true);
по-умолчанию - false
перед началом загрузки данных - true
после получения данных/ошибки - false 

посмотри видео

2024-10-16 09:08 UTC, mishanya1111 commented
> откати изменения в withLoadingDelay и не используй его в CardList
> используй флаг fetching для отображенияч спинера
> 
Если мне не использовать withLoadingDelay в CardList, то где мне его использовать?
Вроде бы я и использую флаг fetching (возможно он по другому называется), чтобы засунуть его в withLoadingDelay,
чтобы спинер отображался. Или тут имеется ввиду что мне прям в Card засунуть, либо компоненты либо спинер

2024-10-16 10:59 UTC, msilina-ibagroup-eu commented
> > откати изменения в withLoadingDelay и не используй его в CardList
> > используй флаг fetching для отображенияч спинера
> 
> Если мне не использовать withLoadingDelay в CardList, то где мне его использовать? Вроде бы я и использую флаг fetching (возможно он по другому называется), чтобы засунуть его в withLoadingDelay, чтобы спинер отображался. Или тут имеется ввиду что мне прям в Card засунуть, либо компоненты либо спинер

вообще не используй withLoadingDelay, раз добавил fetching

2024-10-17 12:47 UTC, msilina-ibagroup-eu requested changes

2024-10-17 12:47 UTC, msilina-ibagroup-eu commented on src/сomponents/CardList.js
>  const CardWithLoading = withLoadingDelay(Card);
withLoadingDelay симулирует ожидание ответа от бэка - в течение 2 сек отображается спинер
ты добавил флаг fetching, который позволяет отображать спинер, пока мы ждем ответа от бэка

следовательно, теперь в CardList ты можешь использовать комронент Card, без твоего кастомного хука. Он больше не нужен

2024-10-17 12:47 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +            setFetching(true);
вынеси из функции

2024-10-17 12:47 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +                setData(resData);
после получения данных setFetching(false);

2024-10-17 12:47 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +                setErrorFetching(true);
после получения ошибки setFetching(false);

2024-10-17 12:47 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +    const [errorFetching, setErrorFetching] = useState(false);
ты должен отображать ошибку, которую получаешь. Сообщение должно быть информативным

2024-10-17 12:47 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +        if (errorFetching) {
это не нужно

2024-10-17 12:47 UTC, msilina-ibagroup-eu commented on src/сomponents/CardList.js
>          <>
такой код тяжело читать. Лучше сделать так
```
loading ? (
    // display spinner
) : (
    <>
        {error && <p>{error.message}</p>}
        {!error &&
            // render cards
        }
    </>
);
```

2024-10-18 09:51 UTC, mishanya1111 commented on src/context/сardArrayContext.js
> +                setData(resData);
Так а зачем после каждого действия?Я вынес после блока Try Catch
```
async function fetchData() {
        setFetching(true);
        try {
            const apiUrl =
              'https://raw.githubusercontent.com/BrunnerLivio/PokemonDataGraber/master/output.json';
            const resp = await axios.get(apiUrl);
            const allCards = resp.data;
            const resData = allCards.slice(0, 15).map(el => {
                return {
                    id: el.Number,
                    title: el.Name,
                    text: el.About,
                    isActive: false
                };
            });
            setData(resData);
        } catch (err) {
            setErrorFetching(true);
            //alert(`The data was not fetch\nError message:${err.message}`);
        }
        setFetching(false);
    }
    ```

2024-10-18 10:10 UTC, mishanya1111 commented on src/context/сardArrayContext.js
> +        if (errorFetching) {
Стоит удалить? Я подумал, это как раз таки хорошо, данные не подгрузились, но если надо ,то обезвредить ошибку

2024-10-18 10:11 UTC, mishanya1111 commented on src/context/сardArrayContext.js
> +                setData(resData);
можно finaly добавить

2024-10-22 12:32 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +        if (errorFetching) {
если ты хочешь предотвратить появление ошибок из-за нажатия на кнопки в то время, пока данные грузятся или, если возникла ошибка, - скрывай кнопки или задизейбли их. В сам метод ничего добавлять не нужно

2024-10-22 12:38 UTC, msilina-ibagroup-eu requested changes

2024-10-22 12:38 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +    const [errorFetching, setErrorFetching] = useState(false);
почему тут дефолтное значение false, при этом в fetchData ты кладешь туда error, а называется переменная errorFetching? что errorFetching делает?

2024-10-23 08:54 UTC, mishanya1111 commented on src/context/сardArrayContext.js
> +    const [errorFetching, setErrorFetching] = useState(false);
![Screenshot_2024-10-23-11-49-55-979_com.github.android.jpg](https://github.com/user-attachments/assets/763a3f4f-8a5e-4136-ae4c-18e49a4ff65a)

Когда вылавливается ошибка в эту переменную заносится сама ошибка. И в CardList обрабатывается примерно так:
{errorfech && <h4>error.message<h4>}
{!errorfech && ...}

P S.: Писал с телефона, возможно ошибся в названиях

2024-10-23 10:05 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +    const [errorFetching, setErrorFetching] = useState(false);
я спрашиваю, почему переменная называется errorFetching, если в ней хранится error? при чем здесь fetching?

2024-10-23 10:09 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +    const [errorFetching, setErrorFetching] = useState(false);
FYI: If you don’t pass an initial value, the state will be initialized as undefined

2024-10-23 11:37 UTC, mishanya1111 commented on src/context/сardArrayContext.js
> +    const [errorFetching, setErrorFetching] = useState(false);
> я спрашиваю, почему переменная называется errorFetching, если в ней хранится error? при чем здесь fetching?

Первоначально предполагалось что она будет ловить ошибку. Справедливо что слова fetching не верное. Переименную

2024-10-23 13:07 UTC, mishanya1111 commented on src/context/сardArrayContext.js
> +    const [errorFetching, setErrorFetching] = useState(false);
Сейчас я подумал и понял, что название было придумана,в связи с тем ,что это переменнаяя ловит ошибку при извлечении данных. Если я её просто назову error, будет плохо. Из альтернатив я бы предложил errorFethingData errorExtractingData, errorRetrievingData,

2024-10-23 15:05 UTC, msilina-ibagroup-eu commented on src/context/сardArrayContext.js
> +    const [errorFetching, setErrorFetching] = useState(false);
"Если я её просто назову error, будет плохо"
почему переменную, которая хранит ошибку, нельзя назвать error? в фунции, которая не обрабатывает никакие другие ошибки
почему тогда переменная, которая хранит данные, называется просто data, а не dataReceivedAfterExecutingTheRequest?

2024-10-24 18:32 UTC, mishanya1111 commented
В cardList переименовать?там оно называется errorFetch

2024-10-25 10:27 UTC, msilina-ibagroup-eu requested changes
1. я попросила вынести `setFetching(true);` из `fetchData` функции. Зачем ты вынес `fetchData` из `useEffect`? Она нужна где-то еще?
2. зачем в `addNewCard` сетится ошибка, которую ты получаешь, загружая данные в `useEffect`? какое отношение добавление карточки имеет к ошибке, которая уже сетится в `useEffect` при первом рендере страницы?
3. в `CardList` ты используешь error, а не статус наличия/отсутствия ошибки. Почему бы не переименовать?
4. еще раз: если в setState ничего не передать при инициализации он будет инициализирован как undefined

2024-10-25 12:03 UTC, mishanya1111 commented
По поводу 2 пункта. Идея была в том, что  если данные не загрузились, то при добавлении карточки ошибка нейтрализовалась бы. Убрал эту фичу
Edit 1: если убрать эту фичу, то при нажатии на кнопку карточки добавляется ,а на экране они не отображаются
![image](https://github.com/user-attachments/assets/891b46d1-2a14-437f-80ee-5e6ff261da37)

2024-10-25 12:13 UTC, mishanya1111 commented
По поводу 4 пункта. А где я в setState ничего не написал, или ты про setState(undefined)

2024-10-25 12:46 UTC, msilina-ibagroup-eu commented
> По поводу 2 пункта. Идея была в том, что если данные не загрузились, то при добавлении карточки ошибка нейтрализовалась бы. Убрал эту фичу Edit 1: если убрать эту фичу, то при нажатии на кнопку карточки добавляется ,а на экране они не отображаются ![image](https://private-user-images.githubusercontent.com/60313347/380150985-891b46d1-2a14-437f-80ee-5e6ff261da37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTgzMjMsIm5iZiI6MTcyOTg1ODAyMywicGF0aCI6Ii82MDMxMzM0Ny8zODAxNTA5ODUtODkxYjQ2ZDEtMmExNC00MzdmLTgwZWUtNWU2ZmYyNjFkYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEyMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMzc2MGJiN2JhMjA3ZDYyMGY4Y2JjMzk3NzZhMTZkZGY2NmY2ZWY1MDA2OWJhMGI3YWFmYTMyZmM3MDliMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z6ZuNhsmBCpRBWgiAdsjvWVN4qxym0pYOQTLeFBxLcU)

еще раз:
```если ты хочешь предотвратить появление ошибок из-за нажатия на кнопки в то время, пока данные грузятся или, если возникла ошибка, - скрывай кнопки или задизейбли их. В сам метод ничего добавлять не нужно```
это то, как подобные ошибки предотвращаются на ui. У тебя вообще не должно быть возможности жать на кнопки, если данные еще грузятся или дообще не пришли

2024-10-25 12:48 UTC, msilina-ibagroup-eu commented
> По поводу 4 пункта. А где я в setState ничего не написал, или ты про setState(undefined)

setState(undefined) === setState() - нет необходимости передавать undefined

2024-10-25 12:52 UTC, msilina-ibagroup-eu requested changes
задизейбли или скрой кнопки, если получаешь ошибку при загрузке данных или данные все еще грузятся
![image](https://github.com/user-attachments/assets/9aa7f875-5d3c-4f2b-b5ca-5a50b35ec67a)

2024-10-28 08:19 UTC, msilina-ibagroup-eu approved these changes

2024-10-28 14:33 UTC, merged